-- PayStay database schema (PostgreSQL 16).
--
-- REFERENCE COPY. The API creates these tables itself on first start (EF Core, EnsureCreated),
-- so you do not run this file by hand. It is here so you can read the design, and for the viva.
-- To regenerate it from a running database: database/scripts/dump-schema.sh

CREATE EXTENSION IF NOT EXISTS btree_gist;

-- Guests and the owner. Role is 'Customer' or 'Owner'.
CREATE TABLE "Users" (
    "Id"        uuid NOT NULL,
    "Mobile"    character varying(10) NOT NULL,
    "Name"      character varying(80) NOT NULL,
    "Role"      character varying(16) NOT NULL,
    "IsSample"  boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX "IX_Users_Mobile" ON "Users" ("Mobile");

-- One-time passwords. Only a SHA-256 hash is stored, never the code.
CREATE TABLE "OtpCodes" (
    "Id"        uuid NOT NULL,
    "Mobile"    character varying(10) NOT NULL,
    "CodeHash"  text NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "Attempts"  integer NOT NULL,
    "Used"      boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_OtpCodes" PRIMARY KEY ("Id")
);
CREATE INDEX "IX_OtpCodes_Mobile_CreatedAt" ON "OtpCodes" ("Mobile", "CreatedAt");

-- The 50 rooms. Status is the housekeeping state (Available / Cleaning / Maintenance);
-- "booked" is worked out from Bookings, never stored here.
CREATE TABLE "Rooms" (
    "Id"               integer GENERATED BY DEFAULT AS IDENTITY,
    "Number"           integer NOT NULL,
    "Floor"            integer NOT NULL,
    "Type"             character varying(16) NOT NULL,   -- Standard / Deluxe / Suite
    "Price"            numeric(10,2) NOT NULL,
    "Capacity"         integer NOT NULL,
    "Amenities"        text[] NOT NULL,
    "Status"           character varying(16) NOT NULL,   -- Available / Cleaning / Maintenance
    "StatusFromSample" boolean NOT NULL,
    "StatusUpdatedAt"  timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Rooms" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX "IX_Rooms_Number" ON "Rooms" ("Number");

-- One row per room per stay. Rooms booked together share a GroupId.
CREATE TABLE "Bookings" (
    "Id"           uuid NOT NULL,
    "Code"         character varying(16) NOT NULL,       -- shown to guests, e.g. PS7KQ2M9XA
    "GroupId"      uuid NOT NULL,
    "UserId"       uuid NOT NULL,
    "RoomId"       integer NOT NULL,
    "CheckIn"      date NOT NULL,
    "CheckOut"     date NOT NULL,
    "ArrivalTime"  time without time zone NULL,          -- NULL = guest has not fixed a time
    "Guests"       integer NOT NULL,
    "Price"        numeric(10,2) NOT NULL,               -- nightly rate at booking time
    "Discount"     numeric(10,2) NOT NULL,               -- referral discount, if any
    "Gst"          numeric(10,2) NOT NULL,
    "Total"        numeric(10,2) NOT NULL,
    "ReferralCode" character varying(16) NULL,
    "Status"       character varying(16) NOT NULL,       -- Confirmed / Cancelled
    "IsSample"     boolean NOT NULL,
    "CreatedAt"    timestamp with time zone NOT NULL,
    "CancelledAt"  timestamp with time zone NULL,
    CONSTRAINT "PK_Bookings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Bookings_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Bookings_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX "IX_Bookings_Code" ON "Bookings" ("Code");
CREATE INDEX "IX_Bookings_GroupId" ON "Bookings" ("GroupId");
CREATE INDEX "IX_Bookings_UserId" ON "Bookings" ("UserId");
CREATE INDEX "IX_Bookings_RoomId_CheckIn_CheckOut" ON "Bookings" ("RoomId", "CheckIn", "CheckOut");

-- The database itself refuses two confirmed bookings for one room on overlapping dates.
ALTER TABLE "Bookings" ADD CONSTRAINT bookings_no_overlap
    EXCLUDE USING gist ("RoomId" WITH =, daterange("CheckIn", "CheckOut") WITH &&)
    WHERE ("Status" = 'Confirmed');

-- Housekeeping, in-room dining, cab and city-tour requests made from a booking.
CREATE TABLE "ServiceRequests" (
    "Id"        uuid NOT NULL,
    "BookingId" uuid NOT NULL,
    "Kind"      character varying(16) NOT NULL,          -- Housekeeping / Dining / Cab / Tour
    "Items"     jsonb NOT NULL,                          -- [{"name":"Irani Chai","qty":2,"price":50}]
    "When"      character varying(80) NOT NULL,
    "Note"      character varying(140) NULL,
    "Total"     numeric(10,2) NOT NULL,
    "Status"    character varying(16) NOT NULL,          -- New / Accepted / Done / Cancelled
    "IsSample"  boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ServiceRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ServiceRequests_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE CASCADE
);
CREATE INDEX "IX_ServiceRequests_BookingId" ON "ServiceRequests" ("BookingId");
CREATE INDEX "IX_ServiceRequests_Status_CreatedAt" ON "ServiceRequests" ("Status", "CreatedAt");

-- Codes earned by guests who stay 5+ nights in a row. Friends enter them at checkout for 10% off.
CREATE TABLE "ReferralCodes" (
    "Code"          character varying(16) NOT NULL,
    "OwnerUserId"   uuid NOT NULL,
    "SourceGroupId" uuid NOT NULL,
    "CreatedAt"     timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ReferralCodes" PRIMARY KEY ("Code"),
    CONSTRAINT "FK_ReferralCodes_Users_OwnerUserId" FOREIGN KEY ("OwnerUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);
CREATE INDEX "IX_ReferralCodes_OwnerUserId" ON "ReferralCodes" ("OwnerUserId");
